snowflake:
  Description: SnowflakeDB
  Driver: SnowflakeDSIIDriver
  acct: mda67638.us-east-1
  warehouse: COMPUTE_WH
  SSL: on
  UID: haoyuli
  PWD: x{iYTozecfrHyT>FBe34NmUd

MySQL:
  host : reports-central.crlowiqc9uoe.us-west-2.rds.amazonaws.com
  database : analytics
  user : haoyu.li
  password : Fs6AkTDu8Vw4KLo6